### ISSUE TITLE
Error when running: fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False)

### ISSUE THREAD

**Issue by Ashesham** [1adrianb/face-alignment#100]
When running the command "  fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False)". The following error prompts:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ashesham/.local/lib/python3.5/site-packages/face_alignment-1.0.0-py3.5.egg/face_alignment/api.py", line 66, in __init__
  File "/home/ashesham/.local/lib/python3.5/site-packages/face_alignment-1.0.0-py3.5.egg/face_alignment/detection/sfd/sfd_detector.py", line 45, in __init__
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 's3fd' object has no attribute 'to'

**Comment by Ashesham** [comment]
Thank you it helped!!!
