### ISSUE TITLE
Another issue with Dockerfile: pytorch install fail

### ISSUE THREAD

**Issue by tetelman** [1adrianb/face-alignment#14]
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 67, in save_path
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 58, in save_argv
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 84, in override_temp
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 94, in pushd
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-uh5npp3w/torch-0.1.2.post1/setup.py", line 11, in <module>

RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

Please follow the instructions at http://pytorch.org/ to install with miniconda instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Programming Language :: Python :: 3.6',
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 634, in _tmpdir
    yield str(tmpdir)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 653, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    self.process_distribution(spec, dist, deps)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 634, in _tmpdir
    yield str(tmpdir)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 182, in save_pkg_resources_state
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 67, in save_path
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 58, in save_argv
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 84, in override_temp
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 94, in pushd
    yield saved
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-uh5npp3w/torch-0.1.2.post1/setup.py", line 11, in <module>

RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

Please follow the instructions at http://pytorch.org/ to install with miniconda instead.

The command '/bin/sh -c python setup.py install' returned a non-zero code: 1

**Comment by 1adrianb** [comment]
Hi @tetelman sorry for delay, I wil have a look this weekend.

**Comment by lmiguelmh** [comment]
For a way around take a look to:
https://github.com/1adrianb/2D-and-3D-face-alignment/issues/20#issuecomment-334892151
which basically install `pytorch` from http://pytorch.org

**Comment by 1adrianb** [comment]
Thanks @lmiguelmh It should be fixed now, I haven't got the chance to try it tho.
