### ISSUE TITLE
Detector fails with gray images

### ISSUE THREAD

**Issue by neverUseThisName** [1adrianb/face-alignment#154]
When dealing with single channel images, the following error was raised:
`Traceback (most recent call last):
  File "face_align.py", line 5, in <module>
    lms = fa.get_landmarks_from_directory(dir)
  File "/usr/local/lib/python3.5/dist-packages/face_alignment/api.py", line 223, in get_landmarks_from_directory
    detected_faces = self.face_detector.detect_from_directory(path, extensions, recursive, show_progress_bar)
  File "/usr/local/lib/python3.5/dist-packages/face_alignment/detection/core.py", line 97, in detect_from_directory
    predictions[image_path] = self.detect_from_image(image_path)
  File "/usr/local/lib/python3.5/dist-packages/face_alignment/detection/sfd/sfd_detector.py", line 51, in detect_from_image
    bboxlist = detect(self.face_detector, image, device=self.device)
  File "/usr/local/lib/python3.5/dist-packages/face_alignment/detection/sfd/detect.py", line 20, in detect
    img = img - np.array([104, 117, 123])
ValueError: operands could not be broadcast together with shapes (398,377) (3,)`

**Comment by vinayak618** [comment]
The input to detector is 3 channel, please refer the detector code [here](https://github.com/1adrianb/face-alignment/blob/master/face_alignment/detection/sfd/detect.py) make changes accordingly

**Comment by dwy6626** [comment]
same issue here, I use `get_landmarks_from_directory` to load image
