### ISSUE TITLE
Stop at "Downloading the face detection CNN. Please wait..." 

### ISSUE THREAD

**Issue by Sally-fyk** [1adrianb/face-alignment#155]
Traceback (most recent call last):
  File "detlandmark_imgs.py", line 25, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
  File "/data_1/server/app/anaconda/lib/python3.7/site-packages/face_alignment/api.py", line 66, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "/data_1/server/app/anaconda/lib/python3.7/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 39, in __init__
    os.path.join(path_to_temp_detector))
  File "/data_1/server/app/anaconda/lib/python3.7/urllib/request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "/data_1/server/app/anaconda/lib/python3.7/http/client.py", line 447, in read
    n = self.readinto(b)
  File "/data_1/server/app/anaconda/lib/python3.7/http/client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "/data_1/server/app/anaconda/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/data_1/server/app/anaconda/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/data_1/server/app/anaconda/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)

**Comment by vinayak618** [comment]
Please download the face detector model from [here ](https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth) and place that in working folder of your inference script and run the model

**Comment by Sally-fyk** [comment]
> 
> 
> Please download the face detector model from [here ](https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth) and place that in working folder of your inference script and run the model

Thank you very much! The problem is solved

**Comment by mangotuanzi** [comment]
How do I run the model

**Comment by mangotuanzi** [comment]
> Please download the face detector model from here  and place that in working folder of your inference script and run the model
> 
> Thank you very much! The problem is solved

How do I run the model? Where should I place it in?

**Comment by yfq512** [comment]
@Sally-fyk  Hi, I has down this model, how can run it ? where put it in? need your help!!!

**Comment by Sally-fyk** [comment]
> 
> 
> @Sally-fyk Hi, I has down this model, how can run it ? where put it in? need your help!!!



> 
> 
> @Sally-fyk Hi, I has down this model, how can run it ? where put it in? need your help!!!

**Comment by Sally-fyk** [comment]
> 
> 
> > Please download the face detector model from here  and place that in working folder of your inference script and run the model
> > Thank you very much! The problem is solved
> 
> How do I run the model? Where should I place it in?

maybe “~/.face_alignment/" or somewhere. I can't remember, but you can search "anaconda/lib/python3.7/site-packages/face_alignment/api.py"for details.
