### ISSUE TITLE
AttributeError: 'torch.cuda.FloatTensor' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by 18242360613** [1adrianb/face-alignment#16]
In order to improve the accuracy, make flip_input=True.but I got the error as above! Is this a bug!
here is my code 
# fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=True, enable_cudnn=True,flip_input=True,use_cnn_face_detector=True)
here is the error message
Traceback (most recent call last):
  File "/home/cp/PycharmProjects/EmotiW/preprocess/test.py", line 11, in <module>
    preds = fa.get_landmarks(input)[-1]
  File "/usr/local/lib/python3.5/dist-packages/face_alignment-0.1.0-py3.5.egg/face_alignment/api.py", line 189, in get_landmarks
  File "/usr/local/lib/python3.5/dist-packages/face_alignment-0.1.0-py3.5.egg/face_alignment/utils.py", line 215, in flip
# AttributeError: 'torch.cuda.FloatTensor' object has no attribute 'ndim'

**Comment by 1adrianb** [comment]
Hi @18242360613 it should be fixed now. Can you please check again?

**Comment by 18242360613** [comment]
thanks for your immediate feedback and hard work , @1adrianb the problem was solved.
