### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by wuxiaolianggit** [1adrianb/face-alignment#181]
Traceback (most recent call last):
  File "face_ali.py", line 5, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, face_detector='sfd')
  File "/home/wuxiaoliang/anaconda3/envs/wuxl27/lib/python2.7/site-packages/face_alignment/api.py", line 66, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "/home/wuxiaoliang/anaconda3/envs/wuxl27/lib/python2.7/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 44, in __init__
    self.face_detector.load_state_dict(torch.load(path_to_detector))
  File "/home/wuxiaoliang/anaconda3/envs/wuxl27/lib/python2.7/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/wuxiaoliang/anaconda3/envs/wuxl27/lib/python2.7/site-packages/torch/serialization.py", line 410, in _load
    magic_number = pickle_module.load(f)
EOFError

could you tell me how to solve the problem? @siarez

**Comment by 1adrianb** [comment]
@wuxiaolianggit  
I assume you are downloading this from china?
This seams to be an issue with the speed/connection to my webservers for people accessing it from there. Please see: https://github.com/1adrianb/face-alignment/issues/62

**Comment by wuxiaolianggit** [comment]
Thank you very much for your  reply   @1adrianb
