### ISSUE TITLE
errors on python3.8 pytorch1.6 cuda10.2

### ISSUE THREAD

**Issue by RegisWu** [1adrianb/face-alignment#244]
Hi, I follow the instructions to install latest version of face_alignment and run it to detect facial landmarks. But it reports errors as following, could you please give me some advice to solve this problem? Thanks!

My environment is python3.8 + pytorch16 + cuda10.2 (install with pip install face-alignment)

>>> import face_alignment
>>>
>>> from skimage import io
>>> fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
>>>
>>> input = io.imread('/home/reg/Project/DECA/TestSamples/examples/IMG_0392_inputs.jpg')
>>>
>>> preds = fa.get_landmarks(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/face_alignment/api.py", line 101, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/face_alignment/api.py", line 120, in get_landmarks_from_image
    detected_faces = self.face_detector.detect_from_image(image.copy())
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 44, in detect_from_image
    bboxlist = detect(self.face_detector, image, device=self.device)[0]
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/face_alignment/detection/sfd/detect.py", line 19, in detect
    return batch_detect(net, img, device)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/face_alignment/detection/sfd/detect.py", line 45, in batch_detect
    bboxlists = get_predictions(List(olist), batch_size)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/dispatcher.py", line 433, in _compile_for_args
    raise e
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/dispatcher.py", line 366, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/dispatcher.py", line 857, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler.py", line 602, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler.py", line 352, in compile_extra
    return self._compile_bytecode()
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler.py", line 414, in _compile_bytecode
    return self._compile_core()
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler.py", line 394, in _compile_core
    raise e
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler.py", line 385, in _compile_core
    pm.run(self.state)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/typed_passes.py", line 449, in run_pass
    NativeLowering().run_pass(state)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/typed_passes.py", line 375, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/lowering.py", line 242, in create_cpython_wrapper
    self.context.create_cpython_wrapper(self.library, self.fndesc,
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/cpu.py", line 162, in create_cpython_wrapper
    builder.build()
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/callwrapper.py", line 122, in build
    self.build_wrapper(api, builder, closure, args, kws)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/callwrapper.py", line 187, in build_wrapper
    obj = api.from_native_return(retty, retval, env_manager)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/pythonapi.py", line 1389, in from_native_return
    out = self.from_native_value(typ, val, env_manager)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/pythonapi.py", line 1403, in from_native_value
    return impl(typ, val, c)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/core/boxing.py", line 397, in box_array
    np_dtype = numpy_support.as_dtype(typ.dtype)
  File "/home/reg/anaconda3/envs/pytorch16/lib/python3.8/site-packages/numba/np/numpy_support.py", line 151, in as_dtype
    raise NotImplementedError("%r cannot be represented as a Numpy dtype"
NotImplementedError: Failed in nopython mode pipeline (step: nopython mode backend)
list(list(float64)<iv=None>)<iv=None> cannot be represented as a Numpy dtype

**Comment by 1adrianb** [comment]
@RegisWu could you try from source please?

**Comment by RegisWu** [comment]
@1adrianb I tried to reinstall from source and the problem is solved now. Many thanks!

**Comment by chenmingjiongjiong** [comment]
@1adrianb I got the same error today, on python 3.8.5 pytorch-cpu 1.7.1 numba 0.51.2.
(I installed face_alignment using conda)

**Comment by 1adrianb** [comment]
@chenmingjiongjiong are you sure that you are using the latest version? Try printing face_alignment.__version__
The above error is triggered in the SFD detector, which shouldn't be possible since that code path was removed.

**Comment by chenmingjiongjiong** [comment]
@1adrianb I'm using 1.3.2. But I see the latest release on github is 1.3.2?

**Comment by 1adrianb** [comment]
@chenmingjiongjiong Please upgrade to 1.3.3 or install from source
