### ISSUE TITLE
SystemError: CPUDispatcher(<function _get_preds_fromhm at 0x7fc50e018440>) returned a result with an error set

### ISSUE THREAD

**Issue by shash29-dev** [1adrianb/face-alignment#288]
installed using setup.py
and,
running  ---> preds = fa.get_landmarks(input)  gives error:
TypeError: expected dtype object, got 'numpy.dtype[float32]'

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vision3d/anaconda3/lib/python3.7/site-packages/face_alignment-1.3.4-py3.7.egg/face_alignment/api.py", line 110, in get_landmarks
  File "/home/vision3d/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/vision3d/anaconda3/lib/python3.7/site-packages/face_alignment-1.3.4-py3.7.egg/face_alignment/api.py", line 170, in get_landmarks_from_image
  File "/home/vision3d/anaconda3/lib/python3.7/site-packages/face_alignment-1.3.4-py3.7.egg/face_alignment/utils.py", line 201, in get_preds_fromhm
SystemError: CPUDispatcher(<function _get_preds_fromhm at 0x7fc50e018440>) returned a result with an error set

```
info:
Ubuntu 16
nvidia-smi 465 drivers
cuda-8.0
python 3.7

what may be the issue and how to resolve?

**Comment by 1adrianb** [comment]
This is likely due to an incompatibility between numba and numpy. Please make sure you are using the latest versions.

**Comment by iiHeys** [comment]
> This is likely due to an incompatibility between numba and numpy. Please make sure you are using the latest versions.

Problem solved.Thank you!
