### ISSUE TITLE
error: Installed distribution six 1.9.0 conflicts with requirement six>=1.10

### ISSUE THREAD

**Issue by Fung-yuantao** [1adrianb/face-alignment#6]
Environment:
1. CentOS 7
2. Python 2.7.5

I have installed pyTorch using the following commands from [pytorch.org](pytorch.org):
```
pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl
pip install torchvision 
```

Then I clone this project and start to install as follows:
```
pip install -r requirements.txt
python setup.py install
```

When running `pip install -r requirements.txt`, the installation process stopped because of dependencies of boost and python-devel. So I also installed these dependencies:
```
yum install boost-devel.x86_64
yum install python-devel.x86_64 
```

Then I run `pip install -r requirements.txt` again and this time it was successfully installed.
But when I tried to run `python setup.py install`, I got the following error:
```
[root@localhost face-alignment]# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to face_alignment.egg-info/requires.txt
writing face_alignment.egg-info/PKG-INFO
writing top-level names to face_alignment.egg-info/top_level.txt
writing dependency_links to face_alignment.egg-info/dependency_links.txt
reading manifest file 'face_alignment.egg-info/SOURCES.txt'
writing manifest file 'face_alignment.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/face_alignment
copying build/lib/face_alignment/__init__.py -> build/bdist.linux-x86_64/egg/face_alignment
copying build/lib/face_alignment/api.py -> build/bdist.linux-x86_64/egg/face_alignment
copying build/lib/face_alignment/models.py -> build/bdist.linux-x86_64/egg/face_alignment
copying build/lib/face_alignment/utils.py -> build/bdist.linux-x86_64/egg/face_alignment
byte-compiling build/bdist.linux-x86_64/egg/face_alignment/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/face_alignment/api.py to api.pyc
byte-compiling build/bdist.linux-x86_64/egg/face_alignment/models.py to models.pyc
byte-compiling build/bdist.linux-x86_64/egg/face_alignment/utils.py to utils.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying face_alignment.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying face_alignment.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying face_alignment.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying face_alignment.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying face_alignment.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying face_alignment.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/face_alignment-0.1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing face_alignment-0.1.0-py2.7.egg
Removing /usr/lib/python2.7/site-packages/face_alignment-0.1.0-py2.7.egg
Copying face_alignment-0.1.0-py2.7.egg to /usr/lib/python2.7/site-packages
face-alignment 0.1.0 is already the active version in easy-install.pth

Installed /usr/lib/python2.7/site-packages/face_alignment-0.1.0-py2.7.egg
Processing dependencies for face-alignment==0.1.0
error: Installed distribution six 1.9.0 conflicts with requirement six>=1.10
```

I googled this but learned nothing.
Also I tried running the example from `example/`, but it failed:
```
[root@localhost examples]# python detect_landmarks_in_image.py 
Traceback (most recent call last):
  File "detect_landmarks_in_image.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/lib/python2.7/site-packages/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/lib/python2.7/site-packages/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/site-packages/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named Tkinter
```

**Comment by 1adrianb** [comment]
Can you please try to upgrade six?
``sudo pip install --upgrade six``
and for the last one, this should do it:
``sudo yum install tkinter``

**Comment by Fung-yuantao** [comment]
The two problems solved with your solution. And now I can run the example perfectly.
Thanks!
But I have another problem when trying the code from **Detect 2D facial landmarks in pictures** in your project's homepage:
```
import face_alignment
import scipy.io as io

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, enable_cuda=True, flip_input=False)

input = io.imread('../test/assets/aflw-test.jpg')
preds = fa.get_landmarks(input)
```

Error messages:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    input = io.imread('../test/assets/aflw-test.jpg')
AttributeError: 'module' object has no attribute 'imread'
```
I did install `scipy`. Then I checked the API documentation of scipy.io [https://docs.scipy.org/doc/scipy/reference/tutorial/io.html](https://docs.scipy.org/doc/scipy/reference/tutorial/io.html), but did not find `imread`. So is it because you are using some other versions of `scipy.io` or just a mistake?

I comment line `import scipy.io as io` out , then add `from skimage import io` and it works.

**Comment by 1adrianb** [comment]
I am glad that it worked.
Thanks, you are right it was a mistake in the README. Thanks for noticing it!
