### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by DCpengzf** [1adrianb/face-alignment#60]
>>> preds = fa.get_landmarks(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/face_alignment/api.py", line 177, in get_landmarks
  File "build/bdist.linux-x86_64/egg/face_alignment/utils.py", line 82, in crop
  File "build/bdist.linux-x86_64/egg/face_alignment/utils.py", line 74, in transform
AttributeError: 'module' object has no attribute 'matmul'

**Comment by 1adrianb** [comment]
Hi @DCpengzf ,

Can you please make sure that you have the latest version of pytorch?

Thanks,
Adrian
