### ISSUE TITLE
AttributeError: 'module' object has no attribute 'matmul'

### ISSUE THREAD

**Issue by WangChengLongWilliam** [1adrianb/face-alignment#61]
When i run the .py file in /example,i geting a "matmul" error. 
ERROR:
Traceback (most recent call last):
  File "/home/william/DMS/face-alignment/examples/detect_landmarks_in_image.py", line 11, in <module>
    preds = fa.get_landmarks(input)[-1]
  File "/home/william/DMS/face-alignment/face_alignment/api.py", line 175, in get_landmarks
    inp = crop(image, center, scale)
  File "/home/william/DMS/face-alignment/face_alignment/utils.py", line 81, in crop
    ul = transform([1, 1], center, scale, resolution, True)
  File "/home/william/DMS/face-alignment/face_alignment/utils.py", line 74, in transform
    new_point = (torch.matmul(t, _pt))[0:2]
AttributeError: 'module' object has no attribute 'matmul'

**Comment by WangChengLongWilliam** [comment]
OK,i solve this problem .
because my formal torch version is 0.1.
