### ISSUE TITLE
"Detect 3D facial landmarks"  doesn't work!

### ISSUE THREAD

**Issue by ming222** [1adrianb/face-alignment#77]
Hi, Thank you for sharing your code.
I  met a problem when I test "Detect 3D facial landmarks in pictures" . but "Detect 2D facial landmarks in pictures" works well.
ERROR:
`Traceback (most recent call last):
  File "3d.py", line 8, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=False, flip_input=True)
  File "/usr/local/lib/python3.5/dist-packages/face_alignment-0.1.1-py3.5.egg/face_alignment/api.py", line 128, in __init__
  File "/home/yao/.local/lib/python3.5/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/yao/.local/lib/python3.5/site-packages/torch/serialization.py", line 476, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: unexpected EOF. The file might be corrupted.
`
 vesion: python 3.5  pytorch 0.4  ubuntu 16.04
I will be very happy to get your advice!

**Comment by 1adrianb** [comment]
Sorry for huge delay, you probably sorted this out by now, but for reference most likely the 3D model was not downloaded succesfully you will need to redownload it.
