### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by LalitPradhan** [1adrianb/face-alignment#9]
I get the following error. I'm using python 2.7, CUDA 7.5

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/face_alignment/__init__.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/face_alignment/api.py", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS

**Comment by 1adrianb** [comment]
Hi @LalitPradhan,

This is known issue when importing multiple libraries (see for example https://github.com/pytorch/pytorch/issues/2083). You can either try to shuffle the order of the packages you are importing or remove the ones that are not needed.
